from pathlib import Path
b=Path(r"C:\Users\rauna\Desktop\Projects\Meal-Tracking-App/app/src/main/java/com/kalotracker/app")
p=b/"feature/barcode/BarcodeScannerScreen.kt";s=p.read_text(encoding="utf8")
s=s.replace("import androidx.compose.foundation.background", "import androidx.compose.foundation.rememberScrollState\nimport androidx.compose.foundation.verticalScroll\nimport androidx.compose.foundation.background")
s=s.replace('text = "Couldn\'t find this product",', 'text = if (state.reviewLabelUrl != null) "Check this product label" else "Couldn\'t find this product",')
s=s.replace("                    onConfirm = {\n", "                    onConfirm = {\n                        if (!state.canLog) return@ScannedProductCard\n")
s=s.replace("    Box(\n        modifier = modifier\n            .fillMaxWidth()\n            .clip(RoundedCornerShape(topStart", "    val uriHandler = androidx.compose.ui.platform.LocalUriHandler.current\n    val maxHeight = androidx.compose.ui.platform.LocalConfiguration.current.screenHeightDp.dp * 0.85f\n    Box(\n        modifier = modifier\n            .fillMaxWidth()\n            .heightIn(max = maxHeight)\n            .navigationBarsPadding()\n            .clip(RoundedCornerShape(topStart")
s=s.replace("        Column {\n            com.kalotracker.app.core.designsystem.components.DateTimeChip", "        Column(modifier = Modifier.verticalScroll(rememberScrollState())) {\n            com.kalotracker.app.core.designsystem.components.DateTimeChip")
s=s.replace('Text("Check the product and pack size against your packet. Label photos need internet.")', 'Text("Check the product and pack size against your packet. Label photos need internet.")\n                TextButton(onClick = { uriHandler.openUri("https://openfoodfacts.github.io/documentation/docs/Product-Opener/api/") }) { Text("Data source and licenses") }')
p.write_text(s,encoding="utf8")
